version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: medium_nest
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=monari
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - 5400:5432
