version: '3.1'

services:
  db:
    image: postgres:alpine
    container_name: post_nest
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=monari
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
